package client.message;

public enum MES_TYPE {
    GET_LAN,
    CREATE_ROUTER,
    CREATE_NIC,
    CREATE_SWITCH,
    REMOVE_ELEMENT,
    GET_ELEMENT_INFO,
    CONFIGURE_ELEMENT,
    CONNECT_ELEMENTS,
    DISCONNECT_ELEMENTS,
    ERROR
}
